// Generated by CoffeeScript 1.12.0
(function() {
  (function() {
    return this;
  })().tela = {};

  $.getScript("js/jquery/ws", function() {
    tela.ws.cn({
      open: function() {
        var cuore;
        for (cuore in tela.ws.rc) {
          tela.ws.rc[cuore]();
        }
        $(window).hashchange();
        return console.log("open");
      },
      message: function(mj) {
        var md, results;
        results = [];
        for (md in mj) {
          if (tela.ws.on[md] != null) {
            results.push(tela.ws.on[md](mj[md]));
          } else {
            results.push(console.log("por favor, no mod " + md));
          }
        }
        return results;
      }
    });
    return $(document).ready(function() {

      /*
      		$("body").css
      			"padding": "0"
      			"margin": "0"
      			"border": "none"
      		tela.tag = (queta)->
      			$(document.createElement(queta))
       */
      $("head").append([
        $(document.createElement("script")).attr({
          type: "text/javascript"
        }).load("js/jquery/luce")
      ]);
      return $.getScript("js/jquery/hash", function() {
        return $(window).hashchange(function() {
          var hash;
          hash = window.location.hash.split("#");
          if (hash[0] === "") {
            hash.shift();
          }
          if (hash[hash.length - 1] === "") {
            hash.pop();
          }
          return tela.hash(hash);
        });
      });
    });
  });

}).call(this);
