// Generated by CoffeeScript 1.12.0
(function() {
  tela.req = function(cabeza, url, callback) {
    if (cabeza == null) {
      return $.getScript(url, callback);
    } else {
      return callback();
    }
  };

  tela.hash = function(hash) {
    if (hash[0] != null) {
      if (tela.hash[hash[0]] != null) {
        return tela.hash[hash.shift()](hash);
      } else {
        return alert("no manejamos " + cabeza);
      }
    } else {
      return window.location.hash = "igo";
    }
  };

  tela.hash.igo = function(hash) {
    return tela.req(tela.igo, "js/jquery/igo", function() {
      if (tela.igo.hash[hash.length] != null) {
        return tela.igo.hash[hash.length](hash);
      } else {
        return alert("no manejamos esa cantidad de argumentos");
      }
    });
  };

}).call(this);
