// Generated by CoffeeScript 1.12.0
(function() {
  var slice = [].slice;

  tela.tag = function(queta) {
    return $(document.createElement(queta));
  };

  tela.luce = {
    color: function(v) {
      var i;
      if (tela.luce.color[v] == null) {
        tela.luce.color[v] = "#" + (((function() {
          var j, results;
          results = [];
          for (i = j = 1; j <= 6; i = ++j) {
            results.push(v);
          }
          return results;
        })()).join(""));
      }
      return tela.luce.color[v];
    },
    parche: function(color) {
      return tela.tag("table").addClass("parche").css({
        borderRadius: "0.5vmin",
        padding: 0,
        margin: 0,
        boxShadow: "0px 0px 1vmin 0px gray"
      });
    },
    boton: function() {
      var clases;
      clases = 1 <= arguments.length ? slice.call(arguments, 0) : [];

      /*
      			el = $(["","boton"].merge(clases).join("."))
      			unless el.length
      				el = tela.luce.parche().addClass(clases.join(" ")).css(
      					backgroundColor: tela.luce.color("E")
      					fontSize: "3.5vmin"
      					fontFamily: "mono"
      				)
       */
      return (function(el) {
        return {
          ando: function() {},
          ado: function() {
            return el.css({
              boxShadow: "0px 0px 1vmin 0px gray inset"
            }).addClass("ado");
          },
          ante: function() {
            return el.css({
              boxShadow: "0px 0px 1vmin 0px gray"
            }).addClass("ante");
          }
        };
      })((function(el) {
        return {
          "true": function() {
            return el;
          },
          "false": function() {
            return tela.luce.parche().addClass(clases.join(" ")).css({
              backgroundColor: tela.luce.color("E"),
              fontSize: "3.5vmin",
              fontFamily: "mono",
              transition: "500ms"
            });
          }
        }[el.length]();
      })($(["", "boton"].merge(clases).join("."))));
    }
  };

  $("body").css({
    "padding": "0",
    "margin": "0",
    "border": "none"
  }).append([
    tela.luce.parche().css({
      backgroundColor: tela.luce.color("B")
    })
  ]);

  console.dir(tela.luce.boton("conect"));


  /*
   */

  console.log("saludo");


  /*
  
  		boton
  			ando
  			ante
  			ado 
  
  		boton().ando()
  
  		tone = boton()
  		tone.ando()
   */

}).call(this);
