// Generated by CoffeeScript 1.12.0
(function() {
  var leo, sirvo;

  sirvo = function(tipo) {
    return function(dozoi) {
      return function(frango) {
        return frango[tipo](dozoi);
      };
    };
  };

  sirvo.jquery = sirvo("js");

  sirvo.vendor = sirvo("vendor");

  leo = sirvo("html")("html");

  leo.js = sirvo.jquery("comensal.js");

  leo.js.jquery = sirvo.vendor("jquery-2.1.4.min.js");

  leo.js.hash = sirvo.vendor("jquery.ba-hashchange.min.js");

  leo.js.jquery.hash = sirvo.jquery("hash.jquery.js");

  leo.js.jquery.ws = sirvo.jquery("ws.jquery.js");

  leo.js.jquery.luce = sirvo.jquery("luce.jquery.js");

  leo.js.jquery.igo = function(sirvo) {
    return sirvo.ecma("igo")("igo.jquery.js");
  };

  leo.health = sirvo("salud")(200);

  leo.info = {
    gen: sirvo("genpoll")("/info/gen"),
    poll: sirvo("genpoll")("/info/poll")
  };

  module.exports = leo;

}).call(this);
