// Generated by CoffeeScript 1.12.0
(function() {
  var sirvo;

  sirvo = function(intento) {
    return function(como) {
      return function(tipo) {
        return function(formato) {
          return function(charset) {
            return function(lugar) {
              return function(documento) {
                return function(servido) {

                  /*
                  						// is the real shit :-)
                  						// cagamos en el mismo sitio // no lo olvides // :-)
                  						// en el mar
                  						// parece ser buena pero sabemos que es mala :-)
                  						// cagar es lo mejor :-)
                  						// no estás hecho para amar la mierda :-)
                  						// es demasiado arrecha para ti :-)
                  						// this is only a test :-)
                  						// yo hago mierda si me dejas abstraerme :-)
                  						// mánda  un mensaje a ese mundo :-)
                  						// for you to make better shit :-)
                  						// we are real chit :-)
                  						// nuestra virtud verdadera
                  						// fíjate hacia dónde va la mierda
                  						// no ensucies a nadie
                  						// is the sacrest thing
                  						// en la mierda está la forma
                  						// cágala bien
                  						// ver con claridad la mierda
                  						// yo también necesito hacer mierda :-)
                  						// tenemos que producir la mierda de la mejor calidad :-)
                  						// me basta con cagar yo solo :-)
                  						// me gusta hacer mierda de calidad
                  						// somos un baile en la mente
                  						// con el dinero puedes cagar
                  						// con la mierda no se juega, no seas cochino :-)
                  						// toda la mierda tiene que ir a algún sitio
                  						// no confundamos
                  						// si nos preocupáramos de la mierda todo saldría natural :-)
                  						// ordenas porque cagar es un asunto serio
                   */
                  return require("fs").readFile([lugar, documento].join("/"), como, function(err, cont) {
                    if (err) {
                      console.log(["ne", "pas", lugar, documento].join(" "));
                      return sirvo.disculpa(servido);
                    } else {
                      servido.writeHead(intento, {
                        "Content-Type": [[tipo, formato].join("/"), charset].join("")
                      });
                      return servido.end(cont);
                    }
                  });
                };
              };
            };
          };
        };
      };
    };
  };

  sirvo.salud = function(intento) {
    return function(res) {
      res.writeHead(intento);
      return res.end();
    };
  };


  /*	//yo.entregar
  #//	yo.sirvo = 
   *	//	yo.sirvo(200)
  
   *	// tengo que abstraer la forma
   *	//yo.doy = function (intento){
  #//	//	return function (preposicion) {
  #//
   *	//}
   *	// todo lo que doy debe ser bello
   *	//yo.no.se = yo.no("utf8")("text/plain")function (sirvo) {
   *	// la flor nace del guano hacia la luz
   */

  sirvo.puta = sirvo(200)(null)("video")("webm")("")("video")("2015-03-03-102121.webm");

  sirvo.utf = function(intento) {
    return sirvo(intento)("utf8");
  };

  sirvo.app = function(formato) {
    return sirvo.utf(200)("application")(formato)("");
  };

  sirvo.svg = sirvo.utf(200)("image")("svg+xml")(";charset=utf-8");

  sirvo.ecma = sirvo.app("ecmascript");

  sirvo.vendor = sirvo.ecma("vendor");

  sirvo.js = sirvo.ecma("jquery");

  sirvo.json = sirvo.app("json")(".");

  sirvo.txt = function(ext) {

    /*
    		//var salida = sirvo.utf("text/"+ext+";charset=utf-8")("html")(res)
    		// objeto o función, como asignarlas a la vez
    		// con la intención arriba para poder ver
    		// enviar mensajes de la luz
    		// enviados a buscar la luz
    		// si te gustara comer mierda fuera una panza
    		// no seas payaso, no la cagues tanto // :-)
    		// trata con respeto y no muestres la mierda
    		// tienes que guardar tus miércoles
    		// busca la luz para que ilumines la mierda
    		// la mierda necesita luz
    		// intención en la mierda con atención a la abstracción
    		// le damos la mierda a la tierra
    		// es la tierra la que hace un proceso con la luz que le dan
    		// las formas se forman por resonancia de ondas
    		// dando energía bien formada
    		// nuestra mierda debe ser el mejor combustible
    		// puera energía formada
    		//console.log("hey")
     */
    return function(intento) {
      return sirvo.utf(intento)("text")(ext)(";charset=utf-8")(".");
    };
  };

  sirvo.disculpa = sirvo.txt("plain")(404)("disculpe");

  sirvo.html = sirvo.txt("html")(200);

  sirvo.genpoll = function(url) {
    return function(res) {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', 'no-cache, no-store');
      return res.end(JSON.stringify(require('./utils/sys-info')[url.slice(6)]()));
    };
  };

  module.exports = sirvo;

}).call(this);
